const dadosComites = [
  // PT-BR
  {
    tema: "Tema a definir",
    comite: "Direitos Humanos",
    modalidade: "Dupla/Individual",
    classroom: "https://classroom.google.com/c/Nzk3MDI1MTc5NTEy?cjc=e723void",
    whatsapp: "",
    pdf: null,
    idioma: "ptbr",
    imagem: "DireitosHumanos_Discutindo_a_Eficácia_das_Intervenções_dos_Organismos_Internacionais_na_Proteção_dos_Direitos_Humanos.JPG",
    sinopse: "Espaço reservado para a sinopse detalhada do comitê de Direitos Humanos, onde serão discutidas as intervenções internacionais.",
  },
  {
    tema: "Tema a definir",
    comite: "Conselho de Segurança",
    modalidade: "Dupla/Individual",
    classroom: "https://classroom.google.com/c/Nzk3MDI1MzgwNzIx?cjc=f43akxp4",
    whatsapp: "",
    pdf: null,
    idioma: "ptbr",
    imagem: "Conselho de Segurança.AVIF",
    sinopse: "Espaço reservado para a sinopse do Conselho de Segurança.",
  },
  {
    tema: "Tema a definir",
    comite: "Conselho de Segurança",
    modalidade: "Dupla/Individual",
    classroom: "https://classroom.google.com/c/Nzk3MDI1MTczNjgx?cjc=xo2cvltp",
    whatsapp: "",
    pdf: null,
    idioma: "ptbr",
    imagem: "Conselho de Segurança.AVIF",
    sinopse: "Espaço reservado para a sinopse do Conselho de Segurança.",
  },
  {
    tema: "Tema a definir",
    comite: "Câmara dos Deputados",
    modalidade: "Dupla/Individual",
    classroom: "https://classroom.google.com/c/Nzk3MDI1NDIzNzA1?cjc=rnsebxrd",
    whatsapp: "",
    pdf: null,
    idioma: "ptbr",
    imagem: "Escala_6x1.JPG",
    sinopse: "Espaço reservado para a sinopse da Câmara dos Deputados.",
  },
  {
    tema: "Tema a definir",
    comite: "Parlamento Americano",
    modalidade: "Dupla/Individual",
    classroom: "https://classroom.google.com/c/Nzk3MDI1NjUyMjUx?cjc=6m5kpzkn",
    whatsapp: "",
    pdf: null,
    idioma: "ptbr",
    imagem: "Parlamento Americano.WEBP",
    sinopse: "Espaço reservado para a sinopse do Parlamento Americano.",
  },

  // English
  {
    tema: "Tema a definir",
    comite: "Human Rights",
    modalidade: "Double/Single",
    classroom: "https://classroom.google.com/c/Nzk3MDI1NTk4NzQz?cjc=ntwzrfid",
    whatsapp: "",
    pdf: null,
    idioma: "en",
    imagem: "ONU Mulheres.jpg",
    sinopse: "Reserved space for the Human Rights committee synopsis.",
  },
  {
    tema: "Tema a definir",
    comite: "Historical Security Council",
    modalidade: "Double/Single",
    classroom: "https://classroom.google.com/c/Nzk3MDI1NzE0ODQ2?cjc=pofkhlng",
    whatsapp: "",
    pdf: null,
    idioma: "en",
    imagem: "Adressing_the_Russian_Civil_War.PNG",
    sinopse: "Reserved space for the Historical Security Council synopsis.",
  },

  // Siglas
  {
    tema: "Tema a definir",
    comite: "Junior Council",
    modalidade: "Dupla/Individual",
    classroom: "https://classroom.google.com/c/Nzk3MDI1NDM4MzM5?cjc=6ox5p33g",
    whatsapp: "",
    pdf: null,
    idioma: "ptbr",
    imagem: "Falta_de_Recursos_2100.JPG",
    sinopse: "Espaço reservado para a sinopse do Junior Council.",
  },
  {
    tema: "Tema a definir",
    comite: "OMS",
    modalidade: "Dupla/Individual",
    classroom: "https://classroom.google.com/c/Nzk3MDI1MzY0NTE4?cjc=5pvv4wwb",
    whatsapp: "",
    pdf: null,
    idioma: "ptbr",
    imagem: "OMS.png",
    sinopse: "Espaço reservado para a sinopse da OMS.",
  },
  {
    tema: "Tema a definir",
    comite: "ECOSOC",
    modalidade: "Dupla/Individual",
    classroom: "https://classroom.google.com/c/Nzk3MDI1MTAxODY4?cjc=yjnpuzsc",
    whatsapp: "",
    pdf: null,
    idioma: "ptbr",
    imagem: "NeoLudismo.JPG",
    sinopse: "Espaço reservado para a sinopse do ECOSOC.",
  },
  {
    tema: "Tema a definir",
    comite: "FAO",
    modalidade: "Dupla/Individual",
    classroom: "https://classroom.google.com/c/Nzk3MDI1NDM4MzM5?cjc=6ox5p33g",
    whatsapp: "",
    pdf: null,
    idioma: "ptbr",
    imagem: "FAO_Discutindo_Impactos_das_MudançasClimáticas.PNG",
    sinopse: "Espaço reservado para a sinopse da FAO.",
  },
  {
    tema: "Tema a definir",
    comite: "OMC",
    modalidade: "Dupla/Individual",
    classroom: "https://classroom.google.com/c/Nzk3MDI1MzE1ODE0?cjc=5v56y5az",
    whatsapp: "",
    pdf: null,
    idioma: "ptbr",
    imagem: "OMC_Abordando_a_Privatização_de_Setores_Essenciais_seus_Impactos_no_Comércio_Internacional.PNG",
    sinopse: "Espaço reservado para a sinopse da OMC.",
  },

  // Especiais
  {
    tema: "Tema a definir",
    comite: "Special",
    modalidade: "Individual",
    classroom: "https://classroom.google.com/c/Nzk3MDI1NjU1NjA5?cjc=wnwukvo7",
    whatsapp: "",
    pdf: null,
    idioma: "en",
    imagem: "SW.webp",
    sinopse: "Reserved space for the Special committee synopsis.",
  },
  {
    tema: "Ordem Paranormal",
    comite: "Especial",
    modalidade: "Individual",
    classroom: "https://classroom.google.com/c/Nzk3MDI1NzIxMjQ2?cjc=a2zozprb",
    whatsapp: "",
    pdf: null,
    idioma: "ptbr",
    imagem: "Ordem.JPG",
    posicao: "left center",
    sinopse: "Espaço reservado para a sinopse do comitê Especial.",
  },
];

export default dadosComites;
