const dadosComites = [
  {
    tema: "Cooperação econômica internacional para mitigar os impactos da automação no mercado de trabalho",
    comite: "ECOSOC (Conselho Econômico e Social das Nações Unidas)",
    modalidade: "Dupla/Individual",
    classroom: "https://classroom.google.com/c/Nzg1NDIyMTA3MDI5?cjc=owsv2ihl",
    whatsapp: "https://chat.whatsapp.com/D3O91cYbfWd9dIE83U5Dlr?mode=ems_copy_t",
    pdf: "https://drive.google.com/file/d/1g2-daTrG6_zVWmkS5KEctMAnCTgAFQw9/view?usp=drive_link",
    idioma: "ptbr",
    imagem: "ECOSOC.png",
  },
  {
    tema: "Exploração de petróleo na Floresta Amazônica",
    comite: "COP (Conferência das Partes)",
    modalidade: "Dupla/Individual",
    classroom: "https://classroom.google.com/c/Nzg1NDI4OTczNzg5?cjc=noervbrs",
    whatsapp: "https://chat.whatsapp.com/GC6gUppQcl3B3W4xT7LLXM?mode=ems_copy_t",
    pdf: "https://drive.google.com/file/d/1K2c4qrbajoarNESUbe8KaG8d9zCNth2q/view?usp=drive_link",
    idioma: "ptbr",
    imagem: "COP.png",
  },
  {
    tema: "Educação antidiscriminatória: políticas para combater o racismo e a xenofobia nos sistemas de ensino",
    comite: "Câmara dos Deputados",
    modalidade: "Dupla/Individual",
    classroom: "https://classroom.google.com/c/Njk5ODA1Mzc1Mjc0?cjc=hsfxpyvj",
    whatsapp: "https://chat.whatsapp.com/Eb4KzoPe75wFKGdTwzmOJC?mode=ems_copy_t",
    pdf: "https://drive.google.com/file/d/1Vr9XUirzRLHjEDcFuJ-V2OmNxXtg2Py1/view?usp=drive_link",
    idioma: "ptbr",
    imagem: "Camara dos Deputados.webp",
  },
  {
    tema: "Exploração de crianças e adolescentes através do turismo sexual: O papel da comunidade internacional na prevenção e reabilitação de vítimas",
    comite: "Direitos Humanos",
    modalidade: "Dupla/Individual",
    classroom: "https://classroom.google.com/c/Nzg1NDI4NzA3OTc5?cjc=aaf3w72f",
    whatsapp: "https://chat.whatsapp.com/DeVMgCKhJuoCBVVsJdeQq0?mode=ems_copy_t",
    pdf: "https://drive.google.com/file/d/1VF8iRkIb9eitzYG0DfOCTIOCdzL3TdQr/view?usp=drive_link",
    idioma: "ptbr",
    imagem: "Direitos Humanos.png",
  },
  {
    tema: "Mediação e Reconstrução Frente à Crise na Síria",
    comite:
      "Conselho de Segurança",
    modalidade: "Dupla/Individual",
    classroom: "https://classroom.google.com/c/Nzg1NDI4ODMzMDU4?cjc=ptluvexj",
    whatsapp: "https://chat.whatsapp.com/FQNTxM6DJNq4kyuMDPKe0S?mode=ems_copy_t",
    pdf: "https://drive.google.com/file/d/1MYDRSYmggJ6ylsHuJVJ3rIs-qJF2vWbJ/view?usp=drive_link",
    idioma: "ptbr",
    imagem: "Conselho de Seguranca.png",
  },
  {
    tema: "Garantindo a equidade no acesso a vacinas em possíveis futuras pandemias globais",
    comite: "OMS (Organização Mundial da Saúde)",
    modalidade: "Dupla/Individual",
    classroom: "https://classroom.google.com/c/Njk5ODA1NTAxOTY5?cjc=iotgkujm",
    whatsapp: "https://chat.whatsapp.com/HcDQGgm0zos1htvZBVHEyx?mode=ems_copy_t",
    pdf: "https://drive.google.com/file/d/1vyWMLx4LkG5UthVkQJEE9pwPKORqAdRG/view?usp=drive_link",
    idioma: "ptbr",
    imagem: "OMS.png",
  },
  {
    tema: "Abordando os impactos da indústria pornográfica sobre os direitos e a segurança das mulheres (INSCRIÇÕES FECHADAS!)",
    comite: "ONU Mulheres",
    modalidade: "Dupla/Individual",
    classroom: "https://classroom.google.com/c/Njk5ODA1NDAwMTE4?cjc=jajnw6bm",
    whatsapp: "https://chat.whatsapp.com/ILV3BbJ6FWU52O5aevZOQR?mode=ems_copy_t",
    pdf: "https://drive.google.com/file/d/1KvksGGBQL4ysuDDm4GxDv3Fd-STm1Z8a/view?usp=drive_link",
    idioma: "ptbr",
    imagem: "ONU Mulheres.jpg",
  },
  {
    tema: "O Impacto das Políticas de Taxação nos Estados Unidos: Justiça Fiscal e seus Efeitos Globais",
    comite: "OMC (Organização Mundial do Comércio)",
    modalidade: "Dupla/Individual",
    classroom: "https://classroom.google.com/c/Njk5ODA1Mzc4MjIw?cjc=yurg3v4v",
    whatsapp: "https://chat.whatsapp.com/FCwUCT22wmrJgpYHlSfdiV?mode=ems_copy_t",
    pdf: "https://drive.google.com/file/d/1Q9nidDf1CNgJ7KNgTpOmykiMFAmpQp4v/view?usp=drive_link",
    idioma: "ptbr",
    imagem: "omc.png",
  },
  {
    tema: "Conselho Mediterrâneo-asiático: Dominação Macedônica",
    comite: "HISTÓRICO",
    modalidade: "Dupla/Individual",
    classroom: "https://classroom.google.com/c/Njk5ODA1NDYxMTY2?cjc=pgztmfsd",
    whatsapp: "https://chat.whatsapp.com/Fcnp6IKz1ZKHQNhegq1zQp?mode=ems_copy_t",
    pdf: "https://drive.google.com/file/d/1dRgpvofwZQcQa73MNAjqmAtCwGUSfwqm/view?usp=drive_link",
    idioma: "ptbr",
    imagem: "HISTORICO.webp",
  },
  {
    tema: "Conselho dos Deuses: A Humanidade Deve Ser Preservada ou Extinta (INSCRIÇÕES FECHADAS!)",
    comite: "Comitê Especial",
    modalidade: "Individual",
    classroom: "https://classroom.google.com/c/Njk5ODA1NDc3NzYw?cjc=6h3zpa3p",
    whatsapp: "https://chat.whatsapp.com/IxOW0Cmsb9T9mPP2CIGRDA?mode=ems_copy_t",
    pdf: "https://drive.google.com/file/d/1J3LrUkDqV5RGsMpCzFXfhzokjVV9I4jK/view?usp=drive_link",
    idioma: "ptbr",
    imagem: "Especial.webp",
  },
  {
    tema: "Vietnam as the Frontier of the Cold War",
    comite: "Historical Security Council",
    modalidade: "Double/Single",
    classroom: "https://classroom.google.com/c/Njk5ODA1NTA0MDgw?cjc=t52stknm",
    whatsapp: "https://chat.whatsapp.com/J3SFrols8Gv4hoYpGGNWEf?mode=ems_copy_t",
    pdf: "https://drive.google.com/file/d/1d62Qu47wgdUCNQ88DBc90HouJmFcDYn7/view?usp=drive_link",
    idioma: "en",
    imagem: "HSC.jpg",
  },
  {
    tema: "Addressing the threats to international maritime security posed by Houthi attacks on commercial shipping",
    comite: "Security Council",
    modalidade: "Double/Single",
    classroom: "https://classroom.google.com/c/Njk5ODA1NTQ3MTE1?cjc=7zntzvit",
    whatsapp: "https://chat.whatsapp.com/Dh3Q9boLlfa9sIoVq0Yp7e?mode=ems_copy_t",
    pdf: "https://drive.google.com/file/d/1uwFvcab-tD07AlTjfhsBEfjIzdCtNvRd/view?usp=drive_link",
    idioma: "en",
    imagem: "SC.jpg",
  },
  {
    tema: "Paths to Peace between the Galactic Republic and the Confederacy of Independent Systems",
    comite: "Special Committee - Star Wars",
    modalidade: "Single",
    classroom: "https://classroom.google.com/c/Njk5ODA1NTEzOTk1?cjc=mqnfmkms",
    whatsapp: "https://chat.whatsapp.com/IQsV0zStxsuCH6eabS1PZz?mode=ems_copy_t",
    pdf: "https://drive.google.com/file/d/1qCQEA42HDlWxEX-u2P4UbONvn3XTDK7e/view?usp=drive_link",
    idioma: "en",
    imagem: "SW.webp",
  },
];

export default dadosComites;
