const dadosComites = [
  // PT-BR
  {
    tema: "Influências de conflitos mundiais na garantia e proteção dos diretos humanos e na manutenção do direito internacional",
    comite: "Direitos Humanos",
    modalidade: "Dupla",
    classroom: "https://classroom.google.com/c/Nzk3MDI1MTc5NTEy?cjc=e723void",
    whatsapp: "",
    pdf: null,
    idioma: "ptbr",
    imagem: "Direitos Humanos.jpg",
    sinopse: "Espaço reservado para a sinopse detalhada do comitê de Direitos Humanos, onde serão discutidas as intervenções internacionais.",
  },
  {
    tema: "Analisando o colapso dos regimes de controle nuclear e o risco de uma nova corrida armamentista em um mundo multipolar.",
    comite: "Conselho de Segurança",
    modalidade: "Individual",
    classroom: "https://classroom.google.com/c/Nzk3MDI1MzgwNzIx?cjc=f43akxp4",
    whatsapp: "",
    pdf: null,
    idioma: "ptbr",
    imagem: "Conselho de Segurança.AVIF",
    sinopse: "Espaço reservado para a sinopse do Conselho de Segurança.",
  },
  {
    tema: "Analisando a interferência nas políticas da América Latinas em  anos de Guerra Fria - 1977",
    comite: "C. de Segurança Histórico",
    modalidade: "Individual",
    classroom: "https://classroom.google.com/c/Nzk3MDI1MTczNjgx?cjc=xo2cvltp",
    whatsapp: "",
    pdf: null,
    idioma: "ptbr",
    imagem: "Conselho de Segurança Histórico.png",
    sinopse: "Espaço reservado para a sinopse do Conselho de Segurança.",
  },
  {
    tema: "Discutindo sobre a jornada de trabalho 6X1 no Brasil",
    comite: "Câmara dos Deputados",
    modalidade: "Individual",
    classroom: "https://classroom.google.com/c/Nzk3MDI1NDIzNzA1?cjc=rnsebxrd",
    whatsapp: "",
    pdf: null,
    idioma: "ptbr",
    imagem: "Câmara dos Deputados.JPG",
    sinopse: "Espaço reservado para a sinopse da Câmara dos Deputados.",
  },
  {
    tema: "Crise de segurança, o combate à imigração irregular e a ação do ICE.",
    comite: "Parlamento Americano",
    modalidade: "Individual",
    classroom: "https://classroom.google.com/c/Nzk3MDI1NjUyMjUx?cjc=6m5kpzkn",
    whatsapp: "",
    pdf: null,
    idioma: "ptbr",
    imagem: "Parlamento Americano.WEBP",
    sinopse: "Espaço reservado para a sinopse do Parlamento Americano.",
  },

  // English
  {
    tema: "Addressing the lack of safety and protection for transgenders people worldwide",
    comite: "Human Rights",
    modalidade: "Double",
    classroom: "https://classroom.google.com/c/Nzk3MDI1NTk4NzQz?cjc=ntwzrfid",
    whatsapp: "",
    pdf: null,
    idioma: "en",
    imagem: "Humans Rights Council.jpg",
    sinopse: "Reserved space for the Human Rights committee synopsis.",
  },
  {
    tema: "Historical Security Council: Adressing the Russian Civil War (1922)",
    comite: "Historical Security Council",
    modalidade: "Single",
    classroom: "https://classroom.google.com/c/Nzk3MDI1NzE0ODQ2?cjc=pofkhlng",
    whatsapp: "",
    pdf: null,
    idioma: "en",
    imagem: "Historical Security Council.PNG",
    sinopse: "Reserved space for the Historical Security Council synopsis.",
  },

  // Siglas
  {
    tema: "Discussing the shortage of resources essential to human life in 2100",
    comite: "Junior ECOSOC",
    modalidade: "Single",
    classroom: "https://classroom.google.com/c/ODY1MzM3MTE3Njc4?cjc=qycf6thv",
    whatsapp: "",
    pdf: null,
    idioma: "en",
    imagem: "Junior ECOSOC.JPG",
    sinopse: "Reserved space for the Junior ECOSOC synopsis.",
  },
  {
    tema: "Discutindo mecanismo para garantir a saúde integral das mulheres em um mundo desigual.",
    comite: "OMS",
    modalidade: "Dupla",
    classroom: "https://classroom.google.com/c/Nzk3MDI1MzY0NTE4?cjc=5pvv4wwb",
    whatsapp: "",
    pdf: null,
    idioma: "ptbr",
    imagem: "OMS.jpeg",
    sinopse: "Espaço reservado para a sinopse da OMS.",
  },
  {
    tema: "Neo-Ludismo: A IA e suas implicações éticas para o trabalho e vida comum em 2053.",
    comite: "ECOSOC",
    modalidade: "Individual",
    classroom: "https://classroom.google.com/c/Nzk3MDI1MTAxODY4?cjc=yjnpuzsc",
    whatsapp: "",
    pdf: null,
    idioma: "ptbr",
    imagem: "ECOSOC 2053.JPG",
    sinopse: "Espaço reservado para a sinopse do ECOSOC.",
  },
  {
    tema: "Debatendo a reforma ágraria como estratégia para garantir a segurança alimentar mundial.",
    comite: "FAO",
    modalidade: "Dupla",
    classroom: "https://classroom.google.com/c/Nzk3MDI1NDM4MzM5?cjc=6ox5p33g",
    whatsapp: "",
    pdf: null,
    idioma: "ptbr",
    imagem: "FAO.PNG",
    sinopse: "Espaço reservado para a sinopse da FAO.",
  },
  {
    tema: "	Abordando a privatização de setores essenciais e seus impactos no comércio internacional.",
    comite: "OMC",
    modalidade: "Individual",
    classroom: "https://classroom.google.com/c/Nzk3MDI1MzE1ODE0?cjc=5v56y5az",
    whatsapp: "",
    pdf: null,
    idioma: "ptbr",
    imagem: "OMC.PNG",
    sinopse: "Espaço reservado para a sinopse da OMC.",
  },

  // Especiais
  {
    tema: "The Trial of Socrates",
    comite: "Special - Trial of Socrates",
    modalidade: "Individual",
    classroom: "https://classroom.google.com/c/Nzk3MDI1NjU1NjA5?cjc=wnwukvo7",
    whatsapp: "",
    pdf: null,
    idioma: "en",
    imagem: "Special - Trial of Socrates.jpg",
    sinopse: "Reserved space for the Special committee synopsis.",
  },
  {
    tema: "Ordem Paranormal: O Paranormal deve ser Controlado ou Apagado?",
    comite: "Especial - Ordem Paranormal",
    modalidade: "Dupla",
    classroom: "https://classroom.google.com/c/Nzk3MDI1NzIxMjQ2?cjc=a2zozprb",
    whatsapp: "",
    pdf: null,
    idioma: "ptbr",
    imagem: "Especial.JPG",
    sinopse: "Espaço reservado para a sinopse do comitê Especial.",
  },
];

export default dadosComites;
